version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongodb_data_container
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongodb_data_container:
